package com.heirloom.core.pipeline;

public enum PipelineEventType {
    INGESTION_REQUESTED,
    RAW_DATA_INGESTED,
    SCHEMA_DISCOVERED,
    DATA_PROFILED,
    SEMANTIC_ALIGNED,
    ENTITIES_RESOLVED,
    ONTOLOGY_PROPOSED,
    PROPOSAL_APPROVED,
    PROPOSAL_REJECTED,
    ONTOLOGY_PUBLISHED
}
